// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"time"
)

type Task struct {
	ID        int64     `db:"id" json:"id"`
	Content   string    `db:"content" json:"content"`
	IsDone    int64     `db:"is_done" json:"isDone"`
	CreatedAt time.Time `db:"created_at" json:"createdAt"`
	DoneAt    time.Time `db:"done_at" json:"doneAt"`
}

type User struct {
	ID             int64     `db:"id" json:"id"`
	Username       string    `db:"username" json:"username"`
	HashedPassword string    `db:"hashed_password" json:"hashedPassword"`
	CreatedAt      time.Time `db:"created_at" json:"createdAt"`
}
